config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  resources :app_settings

  root 'pages#index' 
  get 'edit_theme', to: 'app_settings#edit_theme'
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/app_setting.rb
class AppSetting < ApplicationRecord
  COLOR = %w(
    1
    2
    3
    4
    5
    6
    7
    8
    9
    10
  )


end

app/controllers/app_settings_controller.rb
class AppSettingsController < ApplicationController
  before_action :set_app_setting, only: [:show, :edit, :update, :destroy, :edit_theme]

  # GET /app_settings
  # GET /app_settings.json
  def index
    @app_settings = AppSetting.all
  end

  # GET /app_settings/1
  # GET /app_settings/1.json
  def show
  end

  # GET /app_settings/new
  def new
    @app_setting = AppSetting.new
  end

  # GET /app_settings/1/edit
  def edit

  end

  # POST /app_settings
  # POST /app_settings.json
  def create
    @app_setting = AppSetting.new(app_setting_params)

    respond_to do |format|
      if @app_setting.save
        format.html { redirect_to @app_setting, notice: 'App setting was successfully created.' }
        format.json { render :show, status: :created, location: @app_setting }
      else
        format.html { render :new }
        format.json { render json: @app_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_settings/1
  # PATCH/PUT /app_settings/1.json
  def update
    respond_to do |format|
      if @app_setting.update(app_setting_params)
        format.html { redirect_to @app_setting, notice: 'App setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_setting }
      else
        format.html { render :edit }
        format.json { render json: @app_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_settings/1
  # DELETE /app_settings/1.json
  def destroy
    @app_setting.destroy
    respond_to do |format|
      format.html { redirect_to app_settings_url, notice: 'App setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_theme

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_setting
      @app_setting = AppSetting.find(1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_setting_params
      params.require(:app_setting).permit(
        :theme_color,
        :hidden_sidebar,
        :boxed_content
        )
    end
end

app/helpers/app_settings_helper.rb
module AppSettingsHelper
end

app/views/app_settings/_form.html.erb
<%= simple_form_for(@app_setting) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <ul>
      <li class="hidden-xs-down">
          <a href="" class="top-nav__themes" data-sa-action="aside-open" data-sa-target=".themes"><i class="zmdi zmdi-palette"></i></a>
      </li>
    </ul>
    <%= link_to "Edit Theme", edit_theme_path, class: 'btn btn-outline-primary' %>
    <%= f.input :theme_color %>
    <%= f.input :hidden_sidebar %>
    <%= f.input :boxed_content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


    <a id='theme_1' href="" class="themes__item active" data-sa-value="1"><img src="<%= asset_url 'img/bg/1.jpg' %>" alt=""></a> 
    <a id='theme_2' href="" class="themes__item" data-sa-value="2"><img src="<%= asset_url 'img/bg/2.jpg' %>" alt=""></a>
    <a id='theme_3' href="" class="themes__item" data-sa-value="3"><img src="<%= asset_url 'img/bg/3.jpg' %>" alt=""></a>
    <a id='theme_4' href="" class="themes__item" data-sa-value="4"><img src="<%= asset_url 'img/bg/4.jpg' %>" alt=""></a>
    <a id='theme_5' href="" class="themes__item" data-sa-value="5"><img src="<%= asset_url 'img/bg/5.jpg' %>" alt=""></a>
    <a id='theme_6' href="" class="themes__item" data-sa-value="6"><img src="<%= asset_url 'img/bg/6.jpg' %>" alt=""></a>
    <a id='theme_7' href="" class="themes__item" data-sa-value="7"><img src="<%= asset_url 'img/bg/7.jpg' %>" alt=""></a>
    <a id='theme_8' href="" class="themes__item" data-sa-value="8"><img src="<%= asset_url 'img/bg/8.jpg' %>" alt=""></a>
    <a id='theme_9' href="" class="themes__item" data-sa-value="9"><img src="<%= asset_url 'img/bg/9.jpg' %>" alt=""></a>
    <a id='theme_10' href="" class="themes__item" data-sa-value="10"><img src="<%= asset_url 'img/bg/10.jpg' %>" alt=""></a>

app/views/app_settings/_reload.html.erb
<script>
$(document).ready(function() {
  window.onload = function() {
    if(!window.location.hash) {
        window.location = window.location + '#loaded';
        window.location.reload();
    }
  }
});
</script>

app/views/app_settings/edit.html.erb
<h1>Editing App Setting</h1>

<%= render 'form', app_setting: @app_setting %>

<%= link_to 'Show', @app_setting %> |
<%= link_to 'Back', app_settings_path %>

app/views/app_settings/edit_theme.html.erb
<header class="content__title">
  <h1>Update Theme</h1>
  <small>Remember to save once a theme color is selected</small>
  <div class="actions">
    <a href="" class="actions__item zmdi zmdi-trending-up"></a>
    <a href="" class="actions__item zmdi zmdi-check-all"></a>
    <div class="dropdown actions__item">
      <i data-toggle="dropdown" class="zmdi zmdi-more-vert"></i>
      <div class="dropdown-menu dropdown-menu-right">
        <a href="" class="dropdown-item">Refresh</a>
        <a href="" class="dropdown-item">Manage Widgets</a>
        <a href="" class="dropdown-item">Settings</a>
      </div>
    </div>
  </div>
</header>
<%= simple_form_for(@app_setting) do |f| %>
  <%= f.error_notification %>
    <a id='theme_1' href="" class="themes__item active" data-sa-value="1"><img src="<%= asset_url 'img/bg/1.jpg' %>" alt=""></a> 
    <a id='theme_2' href="" class="themes__item" data-sa-value="2"><img src="<%= asset_url 'img/bg/2.jpg' %>" alt=""></a>
    <a id='theme_3' href="" class="themes__item" data-sa-value="3"><img src="<%= asset_url 'img/bg/3.jpg' %>" alt=""></a>
    <a id='theme_4' href="" class="themes__item" data-sa-value="4"><img src="<%= asset_url 'img/bg/4.jpg' %>" alt=""></a>
    <a id='theme_5' href="" class="themes__item" data-sa-value="5"><img src="<%= asset_url 'img/bg/5.jpg' %>" alt=""></a>
    <a id='theme_6' href="" class="themes__item" data-sa-value="6"><img src="<%= asset_url 'img/bg/6.jpg' %>" alt=""></a>
    <a id='theme_7' href="" class="themes__item" data-sa-value="7"><img src="<%= asset_url 'img/bg/7.jpg' %>" alt=""></a>
    <a id='theme_8' href="" class="themes__item" data-sa-value="8"><img src="<%= asset_url 'img/bg/8.jpg' %>" alt=""></a>
    <a id='theme_9' href="" class="themes__item" data-sa-value="9"><img src="<%= asset_url 'img/bg/9.jpg' %>" alt=""></a>
    <a id='theme_10' href="" class="themes__item" data-sa-value="10"><img src="<%= asset_url 'img/bg/10.jpg' %>" alt=""></a>
  <div class="form-inputs">
<span class='hidden'><%= f.input :theme_color %></span>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>




  

app/views/app_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>App Settings</h1>

<table>
  <thead>
    <tr>
      <th>Theme color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_settings.each do |app_setting| %>
      <tr>
        <td><%= app_setting.theme_color %></td>
        <td><%= link_to 'Show', app_setting %></td>
        <td><%= link_to 'Edit', edit_app_setting_path(app_setting) %></td>
        <td><%= link_to 'Destroy', app_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App Setting', new_app_setting_path %>

app/views/app_settings/new.html.erb
<h1>New App Setting</h1>

<%= render 'form', app_setting: @app_setting %>

<%= link_to 'Back', app_settings_path %>

app/views/app_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Theme color:</strong>
  <%= @app_setting.theme_color %>
</p>

<%= link_to 'Edit', edit_app_setting_path(@app_setting) %> |
<%= link_to 'Back', app_settings_path %>